#!/usr/bin/env bash
#transfers a file from our client to a server

file=$1
ip=$2
user=$3
key=$4

if [[ "$#" -ne 4 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp "$file" "${user}@${ip}:~" -i "$key"
