#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”

# Update package list and install nginx
apt-get update
apt-get -y install nginx

#Set up server block to return "Hello World!" for path '/'
## Set up server block to return "301 Moved Permanently" rediraction for path '/redirect_me'
cat <<'END' > /etc/nginx/sites-available/default
# Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;
        
        location /redirect_me {
                return 301;
        }

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #try_files $uri $uri/ =404;
                return 200 'Hello World!\n';
        }
}
END

# Restart nginx
service nginx restart
