#!/usr/bin/env bash
#install and setup haproxy on an ubuntu machine

#Update package list and install haproxy
apt-get update
apt-get -y install haproxy

#enable haproxy init script

#configure the haproxy to forward requests to my two servers using the round-robin algorithm
echo "


#my config
frontend web-frontend
        mode tcp
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 123781-web-01 35.153.83.180:80 check
        server 123781-web-02 18.209.223.169:80 check
" >> /etc/haproxy/haproxy.cfg

#restart haproxy
service haproxy restart
