#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
rm ~/hosts.new.copy
awk '
BEGIN {FS="\t"; print "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com"}
$2 ~ /localhost/ {next}
$2 ~ /facbook.com/ {next}
{print $0}
' ~/hosts.new >> ~/hosts.new.copy
cp -f ~/hosts.new.copy /etc/hosts
