#!/usr/bin/env bash
# make nginx run as a user named nginx

pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's[\s*#?\s*user .*[user nginx;[' /etc/nginx/nginx.conf
sed -Ei 's|(listen (\[::\]:)?80) |\180 |' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
